# Generated by Django 5.1 on 2024-08-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('id_number', models.CharField(max_length=8)),
                ('branch', models.CharField(choices=[('------', '------'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Mombasa', 'Mombasa'), ('Eldoret', 'Eldoret'), ('Kisii', 'Kisii'), ('Narok', 'Narok')], default='------', max_length=10)),
                ('gender', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.staffuser')),
            ],
        ),
    ]
