# Generated by Django 5.1 on 2024-08-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'AdminUser'), (2, 'StaffUser'), (3, 'RegionalManager')], default=1),
        ),
    ]
