# Generated by Django 5.1 on 2024-08-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_customerdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='i_d',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='admin',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='i_d',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='admin',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='staffuser',
            old_name='i_d',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='staffuser',
            old_name='admin',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='branch',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Mombasa', 'Mombasa'), ('Eldoret', 'Eldoret'), ('Kisii', 'Kisii'), ('Narok', 'Narok')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'AdminUser'), (2, 'StaffUser'), (3, 'Customer')], default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
